### ISSUE TITLE
How long after Drupal 6 support is dropped will Pressflow 6 be supported?

### ISSUE THREAD

**Issue by rychannel** [pressflow/6#87]

**Comment by fluxsauce** [comment]
For whatever it's worth, I'll keep testing and merging as long as there are official Drupal 6 releases.

**Comment by evandonovan** [comment]
I'm reopening this because it says the following on the D6 LTS project page (https://www.drupal.org/project/d6lts):

If you're looking for full releases of Drupal 6 core with [the LTS] patches included, check out the Pressflow 6 project on GitHub

Does that mean that the answer to this question has changed? I didn't see any statement on pressflow.org itself.

I would hope that my organization will be able to leave D6 behind in the next 3 months or so, but having this as a stopgap is greatly helpful.

**Comment by pwolanin** [comment]
From what I understand the D6 LTS team will make any backported fixes available in patch form on drupal.org.

Given that there will be no actual core tarballs with those fixed,  I now think it would make sense to try to apply any D6 LTS core patches here and make additional pressflow releases, and that general intent is perhaps why mlhess put that note on drupal.org.

**Comment by evandonovan** [comment]
Thanks, pwolanin, that is helpful. I think you can consider this issue fixed now, then.

**Comment by evandonovan** [comment]
It doesn't appear that there have been any backported fixes for D6 core, correct? Does anyone know if there are security vulnerabilities in 6.38 that haven't been resolved?

**Comment by fluxsauce** [comment]
@ochenk thoughts?

**Comment by ochenk** [comment]
@evandonovan @fluxsauce  Yes, I believe that's correct, that no security vulnerabilities have been publicly identified for 6.38. The D6LTS Team will post all D6 security patches here: https://www.drupal.org/project/d6lts and none have been posted since D6's eol.

**Comment by evandonovan** [comment]
Thanks - I just wanted to check because I have 3 D6 sites running Pressflow that I am probably going to be supporting until mid-spring, although I am working on migrating them. I thought maybe some of the recent D7 vulnerabilities would be vectors in D6 as well, but wasn't sure.
